server:
  port: 8989
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id:  debit-service
        uri: https://debit-service-test-kushalbajji-dev.apps.sandbox.x8i5.p1.openshiftapps.com
        predicates:
        - Path=/debit/**
      - id: credit-service
        uri: https://credit-service-test-kushalbajji-dev.apps.sandbox.x8i5.p1.openshiftapps.com
        predicates:
        - Path=/credit/**
      - id: admin-service
        uri: https://admin-service-test-kushalbajji-dev.apps.sandbox.x8i5.p1.openshiftapps.com
        predicates:
        - Path=/admin/**
      - id: user-service
        uri: https://user-service-test-kushalbajji-dev.apps.sandbox.x8i5.p1.openshiftapps.com
        predicates:
        - Path=/users/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://microservices-git-kushalbajji-dev.apps.sandbox.x8i5.p1.openshiftapps.com/eureka/
  instance:
    preferIpAddress: true
       

