server:
  port: 8989
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: debit-service
        uri: lb://DEBIT-SERVICE
        predicates:
        - Path=/debit/**
      - id: credit-service
        uri: lb://CREDIT-SERVICE
        predicates:
        - Path=/credit/**
      - id: admin-service
        uri: lb://ADMIN-SERVICE
        predicates:
        - Path=/admin/**
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://microservices-git-kushalbajji-dev.apps.sandbox.x8i5.p1.openshiftapps.com/eureka/
  instance:
    preferIpAddress: true
       

